/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppFormatterXmlRouteImport } from './routes/_app/formatter.xml'
import { Route as AppFormatterJsonRouteImport } from './routes/_app/formatter.json'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFormatterXmlRoute = AppFormatterXmlRouteImport.update({
  id: '/formatter/xml',
  path: '/formatter/xml',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFormatterJsonRoute = AppFormatterJsonRouteImport.update({
  id: '/formatter/json',
  path: '/formatter/json',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/formatter/json': typeof AppFormatterJsonRoute
  '/formatter/xml': typeof AppFormatterXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/formatter/json': typeof AppFormatterJsonRoute
  '/formatter/xml': typeof AppFormatterXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/formatter/json': typeof AppFormatterJsonRoute
  '/_app/formatter/xml': typeof AppFormatterXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/formatter/json' | '/formatter/xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/formatter/json' | '/formatter/xml'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/formatter/json'
    | '/_app/formatter/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/formatter/xml': {
      id: '/_app/formatter/xml'
      path: '/formatter/xml'
      fullPath: '/formatter/xml'
      preLoaderRoute: typeof AppFormatterXmlRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/formatter/json': {
      id: '/_app/formatter/json'
      path: '/formatter/json'
      fullPath: '/formatter/json'
      preLoaderRoute: typeof AppFormatterJsonRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppFormatterJsonRoute: typeof AppFormatterJsonRoute
  AppFormatterXmlRoute: typeof AppFormatterXmlRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppFormatterJsonRoute: AppFormatterJsonRoute,
  AppFormatterXmlRoute: AppFormatterXmlRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
